// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqakbnqnogwjkelkxzrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxYWtibnFub2d3amtlbGt4enJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTg2MTEsImV4cCI6MjA2NTUzNDYxMX0.op6lF-pg3C2T7FivXnxVNvYlCTuOz6lts86BYsieR7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);